nome = input("Inserisci il nome del tuo personaggio: ")
print()
print("INTRODUZIONE")
print("Ti trovi in volo sul tuo caccia interplanetario.")
print("E'stato un lungo viaggio quello che ti ha portato fino a qui, sulla luna boscosa di Molok")
print("Stai ammirando il panorama che ti circonda quando improvvisamente si accende la spia che segnala una comunicazione in ingresso;")
print("Cosa fai?")
print()
print("A. Rispondo")
print("B. Ignoro la chiamata")
risposta1 = input().upper()

if risposta1 == "A":
  print("Decidi di rispondere alla chiamata;")
  print("Il segnale è molto disturbato ma riesci a capire che è il tuo capo missione.")
  print(nome, "inverti immediatm...grrr...fschhhh...rotta!. SEI IN PERICOLO!")
  print("<...fff..shsssss...tai sorvolando una zona nemica!>")
  print("Cosa fai?")
  print()
  print("A. Inverto la rotta")
  print("B. Proseguo per la mia strada")
  
  risposta2 = input().upper()
  if risposta2 == "A":
    print("Decidi di invertire la rotta.")
  else:
    print("Dopo una valutazione attenta decidi di aumentare il livello di guardia ma di continuare sulla tua rotta.")

print("All'improvviso vedi un lampo nella fitta boscaglia sottostante.")
print("Il rilevatore termico ti segnala che sei seguito da un razzo terra aria.")
print("Cosa fai?")
print()
print("A. Tenti una manovra elusiva per schivare il razzo")
print("B. Ti lanci con il paracadute")
risposta3 = input().upper()
if risposta3 == 'A':
  print("Fiducioso nelle tue capacità di pilota militare decidi di tentare alcune manovre elusive")
  print("Nonostante i tuoi sforzi")

print("il missile si avvicina pericolosamente al tuo velivolo.")
print("Non ti rimane nessuna alternativa; con presa salda afferri la leva di espulsione e la tiri.")
print("In un attimo ti ritrovi fuori dal tuo areo, sospeso in aria con il tuo paracadute.")
print("E'questione di pochi attimi prima che il tuo aereo venga colpito dal razzo. L'esplosione è così forte e vicina che perdi i sensi.")
print()
input("PREMI INVIO PER PROVARE A SVEGLIARTI")
print()
print("........apri gli occhi e ti rendi conto di essere vivo.")
print("E'notte, non sai esattamente in quale punto del pianeta ti trovi, ma per ora poco importa")
print("al momento il tuo problema è riuscire a scendere dall'albero a cui il tuo paracadute è rimasto impigliato.")
print("Quello che succederà dopo lo scoprirete solo nella prossima puntata.")
input("TO BE CONTINUED...")